name: speedflux
services:
  main_app:
    cpu_shares: 10
    command: []
    container_name: speedflux
    deploy:
      resources:
        limits:
          memory: 256M
    environment:
      - INFLUX_DB_ADDRESS=192.168.10.999
      - INFLUX_DB_DATABASE=speedtest
      - INFLUX_DB_USER=speedtest
      - INFLUX_DB_PASSWORD=
      - INFLUX_DB_PORT=8086
      - INFLUX_DB_TAGS=isp, external_ip, server_id, server_name, server_location, speedtest_url
      - LOG_TYPE=info
      - PING_INTERVAL=60
      - PING_TARGETS=1.1.1.1, 8.8.8.8
      - SPEEDTEST_FAIL_INTERVAL=5
      - SPEEDTEST_INTERVAL=150
    image: breadlysm/speedtest-to-influxdb:0.4.1
    labels:
      icon: https://github.com/walkxcode/dashboard-icons/blob/main/png/openspeedtest.png?raw=true
    ports:
      - target: 8086
        published: "8086"
        protocol: tcp
    restart: unless-stopped
    volumes: []
    devices: []
    cap_add: []
    network_mode: bridge
    privileged: false
    hostname: speedflux
x-casaos:
  architectures:
    - amd64
    - arm64
  main: cloudbeaver
  author: urbaxe
  category: Developer
  description:
    en_us: CloudBeaver is a web-based database GUI tool which provides rich web interface. You can use it to manage PostgreSQL, MySQL, MariaDB, SQL Server, Oracle, DB2, Firebird, H2, Trino.
    pt_br: CloudBeaver é uma ferramenta GUI de banco de dados baseada na web que oferece uma interface web abrangente. Você pode usá-lo para gerenciar PostgreSQL, MySQL, MariaDB, SQL Server, Oracle, DB2, Firebird, H2 e Trino.
  hostname: 
  icon: https://github.com/walkxcode/dashboard-icons/blob/main/png/openspeedtest.png?raw=true
  index: /
  port_map: ""
  scheme: https
  store_app_id: speedflux
  title:
    custom: Speedflux
